bdd_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

controlacad/urls.py
from django.contrib import admin
from django.urls import path, include
from Login import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from Login.views import SignupView, RolCreate, RolUpdate, RolModificar


urlpatterns = [
    path('admin/', admin.site.urls),
    # Roles
    path('roles/<int:pk>/editar/', RolUpdate),
    path('roles/<int:pk>/modificar/', RolModificar),
    path('', LoginView.as_view(), name='login'),
    path('roles/', views.RolPage, name='roles'),
    path('create-rol/', views.RolCreate, name='create_rol'),
    # Login - Signup
    path('inicio/', views.HomePage, name='inicio'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Usuarios
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    # Edificios
    path('edificios/', include('edificios.urls', namespace='edificios')),
    # Pensum
    path('inicio/pensum/', include('pensum.urls', namespace="pensum"))
]

edificios/urls.py
from django.urls import path
from .views import (EdificioView, EdificioCrearView, EdificioEditarView,
                    SalonesView, SalonesCrearView, SalonesEditarView,
                    SalonesClasificacionView, SalonesClasificacionCrearView, 
                    SalonesClasificacionEditarView)


app_name = 'edificios'

urlpatterns = [
    #Edificios
    path('', EdificioView.as_view(), name='edificio'),
    path('crear/', EdificioCrearView.as_view(), name='edificio_crear'),
    path('<int:pk>/editar/', EdificioEditarView.as_view(), name='edificio_editar'),
    #Salones
    path('salones/', SalonesView.as_view(), name='salones'),
    path('salones/crear/', SalonesCrearView.as_view(),
         name='salones_crear'),
    path('salones/<int:pk>/editar/', SalonesEditarView.as_view(),
         name='salones_editar'),
    #Clasificación de salones
    path('salones/clasificacion', SalonesClasificacionView.as_view(),
         name='clasificacionSalones'),
    path('salones/clasificacion/crear/',
         SalonesClasificacionCrearView.as_view(), name='salon_clasificacion_crear'),
    path('salones/clasificacion/<int:pk>/editar/',
         SalonesClasificacionEditarView.as_view(), name='salon_clasificacion_editar'),
         
    ]

pensum/urls.py
from django.urls import path
from .views import carrera, crear_carrera, pensum, curso, editar_carrera, crear_curso, editar_curso
from .views import crear_pensum, editar_pensum, ciclo, crear_ciclo, curso_pensum, agregar_curso, editar_curso_pensum

app_name = "pensum"

urlpatterns = [
    path('carrera/', carrera, name='carrera'),
    path('crear_carrera/', crear_carrera, name='crear_carrera'),
    path('editar_carrera/<pk>', editar_carrera, name='editar_carrera'),
    path('crear_pensum/', crear_pensum, name='crear_pensum'),
    path('pensum/<pk>', pensum, name='pensum'),
    path('editar_pensum/<pk>', editar_pensum, name='editar_pensum'),
    path('curso/', curso, name='curso'),
    path('crear_curso/', crear_curso, name='crear_curso'),
    path('editar_curso/<pk>', editar_curso, name='editar_curso'),
    path('ciclo/<pk>', ciclo, name='ciclo'),
    path('crear_ciclo/', crear_ciclo, name='crear_ciclo'),
    path('curso_pensum/<pk>', curso_pensum, name='curso_pensum'),
    path('agregar_curso/', agregar_curso, name='agregar_curso'),
    path('editar_curso_pensum/<pk>', editar_curso_pensum, name='editar_curso_pensum'),
]

usuarios/urls.py
from django.urls import path

from .views import (EstudianteListaView, EstudianteCrearView,
                    EstudianteEditarView, DocenteListaView,
                    DocenteCrearView, DocenteEditarView,
                    UsuarioListaView, UsuarioCrearView,
                    UsuarioEditarView)

app_name = 'usuarios'

urlpatterns = [
    # Estudiantes
    path('estudiantes', EstudianteListaView.as_view(), name='lista-estudiante'),
    path('estudiantes/crear/', EstudianteCrearView.as_view(),
         name='crear-estudiante'),
    path('estudiantes/<int:pk>/editar/',
         EstudianteEditarView.as_view(), name='editar-estudiante'),
    # Docentes
    path('docentes', DocenteListaView.as_view(), name='lista-docente'),
    path('docentes/crear/', DocenteCrearView.as_view(), name='crear-docente'),
    path('docentes/<int:pk>/editar/',
         DocenteEditarView.as_view(), name='editar-docente'),
    # Usuarios
    path('usuarios', UsuarioListaView.as_view(), name='lista-usuario'),
    path('usuarios/crear/', UsuarioCrearView.as_view(), name='crear-usuario'),
    path('usuarios/<int:pk>/editar/',
         UsuarioEditarView.as_view(), name='editar-usuario'),
]

Login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class UsuarioAutenticable(AbstractUser):
    nombre = models.CharField(max_length=20, null=True)
    apellido = models.CharField(max_length=20, null=True)
    correo= models.EmailField(null=True)
    telefono= models.CharField(max_length=20, null=True)
    is_organisor=models.BooleanField(default=True)
    is_agent=models.BooleanField(default=False)
    rol = models.ForeignKey('Rol', on_delete=models.SET_NULL, null=True)


class Rol(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    administrar_carreras = models.BooleanField(default=False)
    administrar_cursos = models.BooleanField(default=False)
    administrar_estudiantes = models.BooleanField(default=False)
    administrar_docentes = models.BooleanField(default=False)
    administrar_usuarios = models.BooleanField(default=False)
    validar_cargas_academicas = models.BooleanField(default=False)
    administrar_roles_y_permisos = models.BooleanField(default=False)
    administracion_de_edificios_y_salones = models.BooleanField(default=False)
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"

Login/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import Rol

Usuario = get_user_model()


class CustomCreationUserForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ("username",
                  'nombre',
                  'apellido',
                  'correo',
                  'telefono',
                  )
        field_classes = {'username': UsernameField}


class RolForm(forms.ModelForm):
    class Meta:
        model = Rol
        fields = (
            'nombre',
            'descripcion',
        )


class RolForm2(forms.ModelForm):
    class Meta:
        model = Rol
        fields = (
            'nombre',
            'descripcion',
            'habilitado'
        )


class RolForm3(forms.ModelForm):
    class Meta:
        model = Rol
        fields = (
            'administrar_carreras',
            'administrar_cursos',
            'administrar_estudiantes',
            'administrar_docentes',
            'administrar_usuarios',
            'validar_cargas_academicas',
            'administrar_roles_y_permisos',
            'administracion_de_edificios_y_salones'
        )

Login/views.py
from django.shortcuts import render
from django.views import generic
from .forms import CustomCreationUserForm, RolForm, RolForm2, RolForm3
from django.shortcuts import render, redirect, reverse
from django.core.mail import send_mail
from .models import Rol
from django.http import HttpResponse

# Create your views here.


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomCreationUserForm

    def get_success_url(self):
        return reverse("login")

def HomePage(request):
    return render(request, 'main/inicio.html')


def LoginPage(request):
    return render(request, 'main/login.html')
    
def RolPage(request):
    roles= Rol.objects.all()
    context = {
        'roles':roles
    }
    return render(request, 'main/roles.html',context)

def RolCreate(request):
    form=RolForm()
    if request.method == "POST":
        form = RolForm(request.POST)
        if form.is_valid():
            print("The form is valid")
            nombre = form.cleaned_data['nombre']
            descripcion = form.cleaned_data['descripcion']
            Rol.objects.create(
                nombre=nombre,
                descripcion=descripcion
        )
        return redirect('roles')
    context = {
        'form':form
    }
    return render(request, 'main/rol_create.html', context)

def RolUpdate(request,pk):
    rol = Rol.objects.get(id=pk)
    form=RolForm2(instance=rol)
    if request.method == "POST":
        form = RolForm2(request.POST, instance=rol)
        if form.is_valid():
            form.save()
            return redirect('roles')
    context = {
        'form':form,
        "rol":rol
    }
    return render(request,"main/rol_update.html", context)

def RolModificar(request,pk):
    rol = Rol.objects.get(id=pk)
    form=RolForm3(instance=rol)
    if request.method == "POST":
        form = RolForm3(request.POST, instance=rol)
        if form.is_valid():
            form.save()
            return redirect('roles')
    context = {
        'form':form,
        "rol":rol
    }
    return render(request,"main/rol_modificar.html", context)

templates/main/inicio.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
Inicio
{% endblock title %}

{% block content %}
<div id="landing">
    <div class="main-content">
        <div class="tk-wrapper">
            <div class="left-column">
                <img id="landing-logo" src="{% static 'images/usaclogo.png' %}">
            </div>
            <div class="right-column">
                <div id="landing-buttons">
                    <h1>Control Académico</h1><br>
                    <h3>Sistema de control de cargas académicas.</h3>
                    <br>
                    <p>Centro Universitario del Norte</p>
                    <p>CUNOR, A.V.</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
        | CUNOR
    </title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
</head>

<body>

    <!-- Barra superior -->
    <div class="nav_info">
        <a href="{% url 'inicio' %}"><img id="logo" src="{% static 'images/usaclogo.png' %}"></a>
        <ul class="infohead">
            <li>PBX (502) 7956 6600 / Extension: 206</li>
            <li>coordinacionacademica@cunor.edu.gt</li>
        </ul>
    </div>

    <!-- Navbar -->
    <header>
        {% if request.user.is_authenticated %}
        <nav>
            <ul class="nav_links">
                <li><a>Conectado como: {{ request.user.username }}</a></li>
                <li><a href="#">Cargas ▾</a>
                    <ul>
                        <li><a href="#">Validación de cargas académicas</a></li>
                    </ul>
                </li>
                <li><a href="#">Pénsum ▾</a>
                    <ul>
                        <li><a href="{% url 'pensum:curso' %}">Cursos</a></li>
                        <li><a href="{% url 'pensum:carrera' %}">Carreras</a></li>
                    </ul>
                </li>
                <li><a href="#">Edificios ▾</a>
                    <ul>
                        <li><a href="{% url 'edificios:edificio' %}">Administración de edificios y salones</a></li>
                    </ul>
                </li>
                <li><a href="#">Usuarios ▾</a>
                    <ul>
                        <li><a href="{% url 'usuarios:lista-estudiante' %}">Administración de estudiantes</a></li>
                        <li><a href="{% url 'usuarios:lista-docente' %}">Administración de docentes</a></li>
                        <li><a href="{% url 'usuarios:lista-usuario' %}">Administración de usuarios</a></li>
                    </ul>
                </li>
                <li><a href="#">Seguridad ▾</a>
                    <ul>
                        <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                        <li><a href="{% url 'reset-password' %}">Cambiar contraseña</a></li>
                        {% if user.is_superuser %}
                        <li><a href="{% url 'roles' %}">Administración de roles y permisos</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </nav>
        {% endif %}
    </header>

    <!-- Contenido -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer>
        <p>PBX: +502 7956 6600</p>
        <p>Correo: informacion@cunor.edu.gt</p>
        <p>Dirección: 7a. calle 1-11 zona 6. Cobán, Alta Verapaz. Código Postal: 16001</p>
        <br>
        <p>201843018 - Giancarlo De León Pérez</p>
        <p>202041906 - Jorge Alejandro Fernández de la Cruz</p>
        <p>202043340 - Jorge Mario Dubón Rosales</p>
        <p>201943148 - Oscar Anibal Sierra Chocooj</p>
        <br>
        <p>&copy; Grupo 1 - Bases de Datos 1 | CUNOR</p>
    </footer>

</body>

</html>

templates/main/login.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Login
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Login</h1>
        </div>
    </div>
</div>

<!--Contenido de la pagina del indice.-->
<div class="logContent">
    <!--
    <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="submitbtn" type="submit">Login</button>
    </form>
    -->
</div>

{% block content %}

templates/main/rol_create.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Roles 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Crear Rol</h1>
      
    </div>
</div>

<!--Contenido de la pagina del indice.-->
<div class="logContent">
    
    <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    
    <a><button class="logbtn" type="submit">Crear</button></a>
    </form>
    <a href="{% url 'roles'%}"><button class="logbtn" >Regresar</button></a>
</div>

{%endblock%}

templates/main/rol_modificar.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Roles 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Modificar Rol</h1>
       
    </div>
</div>

<!--Contenido de la pagina del indice.-->
<div class="logContent">
    
    <table>
    <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    
    <a><button class="logbtn" type="submit">Actualizar</button></a>
    </form>
</table>
<br>
    <a href="{% url 'roles'%}"><button class="logbtn" >Regresar</button></a>
</div>

{%endblock%}

templates/main/rol_update.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Roles 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar Rol</h1>
  
    </div>
</div>

<!--Contenido de la pagina del indice.-->
<div class="logContent">
    
    <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    
    <a><button class="logbtn" type="submit">Actualizar</button></a>
    </form>
    <a href="{% url 'roles'%}"><button class="logbtn" >Regresar</button></a>
</div>

{%endblock%}

templates/main/roles.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Roles 
{% endblock %}

{% block content %}


<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de roles</h1>
    </div>
    <div class="main-box">
     
            <a  href="{% url 'create_rol'%}"><button class="logbtn" >Crear Rol</button></a>
        <table>
            <tr>
              <th>Rol</th>
              <th>Descripcion</th>
              <th>Habilitado</th>
              <th>Opcion</th>
            </tr>

            {% for rol in roles %}
            <tr>
              <td>{{rol.nombre}}</td>
              <td>{{rol.descripcion}}</td>
              <td>{{rol.habilitado}}</td>
              <td><a href="/roles/{{rol.pk}}/editar/" style="color: blue;">Editar</a> | <a href="/roles/{{rol.pk}}/modificar/" style="color: blue;">Modificar</a></td>
            </tr>
            {% endfor %}
          </table>
          <a href="{% url 'inicio'%}"><button class="logbtn" >Regresar</button></a>
    </div>
</div>

{% endblock %}