bdd_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

controlacad/urls.py
from django.contrib import admin
from django.urls import path, include
from Login import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from Login.views import SignupView, RolCreate, RolUpdate, RolModificar


urlpatterns = [
    path('admin/', admin.site.urls),
    # Roles
    path('roles/<int:pk>/editar/', RolUpdate),
    path('roles/<int:pk>/modificar/', RolModificar),
    path('', LoginView.as_view(), name='login'),
    path('roles/', views.RolPage, name='roles'),
    path('create-rol/', views.RolCreate, name='create_rol'),
    # Login - Signup
    path('inicio/', views.HomePage, name='inicio'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Usuarios
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    # Edificios
    path('edificios/', include('edificios.urls', namespace='edificios')),
    # Pensum
    path('inicio/pensum/', include('pensum.urls', namespace="pensum"))
]

pensum/urls.py
from django.urls import path
from .views import carrera, crear_carrera, pensum, curso, editar_carrera, crear_curso, editar_curso
from .views import crear_pensum, editar_pensum, ciclo, crear_ciclo, curso_pensum, agregar_curso, editar_curso_pensum

app_name = "pensum"

urlpatterns = [
    path('carrera/', carrera, name='carrera'),
    path('crear_carrera/', crear_carrera, name='crear_carrera'),
    path('editar_carrera/<pk>', editar_carrera, name='editar_carrera'),
    path('crear_pensum/', crear_pensum, name='crear_pensum'),
    path('pensum/<pk>', pensum, name='pensum'),
    path('editar_pensum/<pk>', editar_pensum, name='editar_pensum'),
    path('curso/', curso, name='curso'),
    path('crear_curso/', crear_curso, name='crear_curso'),
    path('editar_curso/<pk>', editar_curso, name='editar_curso'),
    path('ciclo/<pk>', ciclo, name='ciclo'),
    path('crear_ciclo/', crear_ciclo, name='crear_ciclo'),
    path('curso_pensum/<pk>', curso_pensum, name='curso_pensum'),
    path('agregar_curso/', agregar_curso, name='agregar_curso'),
    path('editar_curso_pensum/<pk>', editar_curso_pensum, name='editar_curso_pensum'),
]

pensum/models.py
from django.db import models


class Carrera(models.Model):
    ciclos = (
        ('Semestral', 'Semestral'),
        ('Trimestral', 'Trimestral'),
        ('Anual', 'Anual')
    )
    grados = (
        ('Técnico', 'Técnico'),
        ('Licenciatura', 'Licenciatura'),
        ('Diplomado', 'Diplomado'),
        ('Especialidad', 'Especialidad'),
        ('Maestría', 'Maestría'),
        ('Doctorado', 'Doctorado'),
    )
    planes = (
        ('Matutina', 'Matutina'),
        ('Vespertina', 'Vespertina'),
        ('Nocturna', 'Nocturna'),
        ('Sábados', 'Sábados'),
        ('Domingos', 'Domingos'),
    )
    nombre = models.CharField(max_length=50)
    duracion = models.IntegerField(default=50)
    clasificacion = models.CharField(max_length=15)
    partida = models.CharField(max_length=15)
    ciclo_academico = models.CharField(choices=ciclos, max_length=100)
    grado_academico = models.CharField(choices=grados, max_length=100)
    jornada = models.CharField(choices=planes, max_length=100)
    encargado_area = models.ForeignKey(
        'usuarios.Docente', on_delete=models.SET_NULL, null=True, related_name='%(class)s_encargado_area')
    coordinador_academico = models.ForeignKey(
        'usuarios.Docente', on_delete=models.SET_NULL, null=True, related_name='%(class)s_coordinador_academico')
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"


class Curso(models.Model):
    codigo = models.CharField(max_length=10)
    nombre = models.CharField(max_length=100)
    horas_semana = models.IntegerField(default=3)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    laboratorio = models.BooleanField(default=False)
    codigo_lab = models.CharField(max_length=10)
    horas_lab = models.IntegerField(default=0)
    semestres = models.IntegerField(default=2)
    habilitado = models.BooleanField(default=True)
    
    def __str__(self):
        return f"{self.nombre}"
    
class Pensum(models.Model):
    codigo = models.CharField(max_length=4)
    inicio = models.IntegerField(default=2023)
    creacion = models.DateField()
    proceso = models.CharField(max_length=250)
    ciclos = models.IntegerField(default=2)
    examen = models.IntegerField(default=100)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    habilitado = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.codigo}"

class Ciclo(models.Model):
    pensum = models.ForeignKey(Pensum, on_delete=models.CASCADE)
    ciclo = models.CharField(max_length=25)

    def __str__(self):
        return f"{self.ciclo}"
    


class CursoPensum(models.Model):
    ciclo = models.ForeignKey(Ciclo, on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, related_name='nombre_curso')
    creditos = models.IntegerField(default=4)
    obligatorio = models.BooleanField(default=True)
    curso_prerrequisito = models.ForeignKey(Curso, on_delete=models.CASCADE, related_name='curso_prerrequisito')
    creditos_prerrequisito = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.curso}"

pensum/forms.py
from django import forms
from .models import Carrera, Curso, Pensum, Ciclo, CursoPensum

class CarreraModelForm(forms.ModelForm):
    class Meta:
        model = Carrera
        fields = (
            'nombre',
            'duracion',
            'clasificacion',
            'partida',
            'ciclo_academico',
            'grado_academico',
            'jornada',
            'encargado_area',
            'coordinador_academico',
            'habilitado',
        )


class CursoModelForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = (
            'codigo',
            'nombre',
            'horas_semana',
            'carrera',
            'laboratorio',
            'codigo_lab',
            'horas_lab',
            'semestres',
            'habilitado',
        )


class PensumModelForm(forms.ModelForm):
    class Meta:
        model = Pensum
        fields = (
            'codigo',
            'inicio',
            'creacion',
            'proceso',
            'ciclos',
            'examen',
            'carrera',
            'habilitado',
        )

class CicloModelForm(forms.ModelForm):
    class Meta:
        model = Ciclo
        fields = (
            'pensum',
            'ciclo'
        )

class CursoPensumModelForm(forms.ModelForm):
    class Meta:
        model = CursoPensum
        fields = (
            'ciclo',
            'curso',
            'creditos',
            'obligatorio',
            'curso_prerrequisito',
            'creditos_prerrequisito'
        )

pensum/views.py
from django.shortcuts import render, redirect

from .models import Curso, Carrera, Pensum, Ciclo, CursoPensum
from .forms import CarreraModelForm, CursoModelForm, PensumModelForm, CicloModelForm, CursoPensumModelForm

#--------- ESPACIO DE CARRERAS ---------

def carrera(request):
    carreras = Carrera.objects.all()
    context = {
        "carreras" : carreras
    }
    return render(request, "pensum/carrera.html", context)

def crear_carrera(request):
    form = CarreraModelForm()
    if request.method == "POST":
        form = CarreraModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form": form
    }
    return render(request, "pensum/crear_carrera.html", context)

def editar_carrera(request, pk):
    carrera = Carrera.objects.get(id=pk)
    form = CarreraModelForm(instance=carrera)
    if request.method == "POST":
        form = CarreraModelForm(request.POST, instance=carrera)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form" : form,
        "carrera" : carrera
    }
    return render(request, "pensum/editar_carrera.html", context)


#--------- ESPACIO DE CURSOS ---------

def curso(request):
    cursos = Curso.objects.all()
    context = {
        "cursos" : cursos
    }
    return render(request, "pensum/curso.html", context)

def crear_curso(request):
    form = CursoModelForm()
    if request.method == "POST":
        form = CursoModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/curso")
    context = {
        "form": CursoModelForm()
    }
    return render(request, "pensum/crear_curso.html", context)

def editar_curso(request, pk):
    curso = Curso.objects.get(id=pk)
    form = CursoModelForm(instance=curso)
    if request.method == "POST":
        form = CursoModelForm(request.POST, instance=curso)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/curso")
    context = {
        "form" : form,
        "curso" : curso
    }
    return render(request, "pensum/editar_curso.html", context)


#--------- ESPACIO DE PENSUM ---------

def pensum(request, pk):
    carrera = Carrera.objects.get(id=pk)
    pensum = Pensum.objects.filter(carrera=carrera.pk)
    print(pensum)
    context = {
        "carrera" : carrera,
        "pensum" : pensum
    }
    return render(request, "pensum/pensum.html", context)

def crear_pensum(request):
    form = PensumModelForm()
    if request.method == "POST":
        form = PensumModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form": PensumModelForm()
    }
    return render(request, "pensum/crear_pensum.html", context)

def editar_pensum(request, pk):
    pensum = Pensum.objects.get(id=pk)
    form = PensumModelForm(instance=pensum)
    if request.method == "POST":
        form = PensumModelForm(request.POST, instance=pensum)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form" : form,
        "pensum" : pensum
    }
    return render(request, "pensum/editar_pensum.html", context)


#--------- ESPACIO DE CICLOS ---------
def ciclo(request, pk):
    pensum = Pensum.objects.get(id=pk)
    ciclo = Ciclo.objects.filter(pensum=pensum.pk)
    context = {
        "pensum" : pensum,
        "ciclo" : ciclo
    }
    return render(request, "pensum/ciclo.html", context)


def crear_ciclo(request):
    form = CicloModelForm()
    if request.method == "POST":
        form = CicloModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form": CicloModelForm()
    }
    return render(request, "pensum/crear_ciclo.html", context)


#--------- ESPACIO DE CURSOS PARA PENSUM ---------
def curso_pensum(request, pk):
    ciclo = Ciclo.objects.get(id=pk)
    curso_pensum = CursoPensum.objects.filter(ciclo=ciclo.pk)
    context = {
        "ciclo" : ciclo,
        "curso_pensum" : curso_pensum
    }
    return render(request, "pensum/curso_pensum.html", context)

def agregar_curso(request):
    form = CursoPensumModelForm()
    if request.method == "POST":
        form = CursoPensumModelForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form": CursoPensumModelForm()
    }
    return render(request, "pensum/agregar_curso.html", context)

def editar_curso_pensum(request, pk):
    curso = CursoPensum.objects.get(id=pk)
    form = CursoPensumModelForm(instance=curso)
    if request.method == "POST":
        form = CursoPensumModelForm(request.POST, instance=curso)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect("/inicio/pensum/carrera")
    context = {
        "form" : form,
        "curso" : curso
    }
    return render(request, "pensum/editar_curso_pensum.html", context)

templates/pensum/agregar_curso.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Agregar curso 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Agregar curso</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:carrera'%}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Agregar curso</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/carrera.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Carreras 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de carreras</h1>
    </div>
    <div class="main-box">
        <table class="main-table">
            <br>
            <a  href="{% url 'pensum:crear_carrera' %}"><button class="logbtn">Crear carrera</button></a>
            <br>
            <tr>
              <th>Nombre de carrera</th>
              <th>Encargado</th>
              <th>Opciones</th>
            </tr>
            {% for carrera in carreras %}
            <tr>
              <td>{{ carrera.nombre }}</td>
              <td>X</td>
              <td>
                <ul>
                    <li><a href="{% url 'pensum:editar_carrera' carrera.pk %}">Editar</a></li>
                    <li><a href="{% url 'pensum:pensum' carrera.pk %}">Administrar pensum</a></li>
                    <li><a href="#">Cargas académicas</a></li>
                </ul>
              </td>
            </tr>
            {% endfor %}
          </table>
        <ul>
        </ul>
    </div>
</div>

{% endblock %}

templates/pensum/ciclo.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Ciclos 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de ciclos</h1>
    </div>
    <h2>Para el pensum: {{ pensum.codigo }} - {{ pensum.inicio }}</h2>
    <div class="main-box">
        <table class="main-table">
            <br>
            <a  href="{% url 'pensum:carrera'%}"><button class="logbtn">Regresar</button></a>
            <br>
            <a  href="{% url 'pensum:crear_ciclo' %}"><button class="logbtn">Crear ciclo</button></a>
            <br>
            <tr>
              <th>Ciclo</th>
              <th>Opciones</th>
            </tr>
            {% for ciclos in ciclo %}
            <tr>
              <td>{{ ciclos.ciclo }}</td>
              <td>
                <ul>
                    <li><a href="{% url 'pensum:curso_pensum' ciclos.pk %}">Agregar cursos</a></li>
                </ul>
              </td>
            </tr>
            {% endfor %}
          </table>
        <ul>
        </ul>
    </div>
</div>

{% endblock %}

templates/pensum/crear_carrera.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Crear carrera 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Crear carrera</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:carrera' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Crear carrera</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/crear_ciclo.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Crear ciclo 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Crear ciclo</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:carrera'%}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Crear ciclo</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/crear_curso.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Crear cursos 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Crear curso</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:curso' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Crear curso</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/crear_pensum.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Crear pensum 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Crear pensum</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:pensum' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Crear pensum</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/curso.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Cursos 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de cursos</h1>
    </div>
    <div class="main-box">
        <table class="main-table">
            <br>
            <a  href="{% url 'pensum:crear_curso' %}"><button class="logbtn">Crear curso</button></a>
            <br>
            <tr>
              <th>Codigo</th>
              <th>Nombre</th>
              <th>Opciones</th>
            </tr>
            {% for curso in cursos %}
            <tr>
              <td>{{ curso.codigo }}</td>
              <td>{{ curso.nombre }}</td>
              <td><a href="{% url 'pensum:editar_curso' curso.pk%}">Editar</a></td>
            </tr>
            {% endfor %}
          </table>
        <ul>
    </div>
</div>

{% endblock %}

templates/pensum/curso_pensum.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Cursos pensum 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de cursos</h1>
    </div>
    <h2>Para: {{ ciclo.ciclo }}</h2>
    <div class="main-box">
        <table class="main-table">
            <br>
            <a  href="{% url 'pensum:carrera'%}"><button class="logbtn">Regresar</button></a>
            <br>
            <a  href="{% url 'pensum:agregar_curso' %}"><button class="logbtn">Agregar curso</button></a>
            <br>
            <tr>
              <th>Curso</th>
              <th>Creditos</th>
              <th>Obligatorio</th>
              <th>Curso prerrequisito</th>
              <th>Creditos prerrequisito</th>
              <th>Opciones</th>
            </tr>
            {% for curso in curso_pensum %}
            <tr>
              <td>{{ curso.curso }}</td>
              <td>{{ curso.creditos }}</td>
              <td>{{ curso.obligatorio }}</td>
              <td>{{ curso.curso_prerrequisito }}</td>
              <td>{{ curso.creditos_prerrequisito }}</td>
              <td>
                <ul>
                    <li><a href="{% url 'pensum:editar_curso_pensum' curso.pk %}">Editar</a></li>   
                </ul>
              </td>
            </tr>
            {% endfor %}
          </table>
        <ul>
        </ul>
    </div>
</div>

{% endblock %}

templates/pensum/editar_carrera.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Editar carrera 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar {{ carrera.nombre }}</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:carrera' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Editar carrera</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/editar_curso.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Editar curso 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar {{ curso.codigo }} - {{ curso.nombre }}</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:curso' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Editar curso</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/editar_curso_pensum.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Editar curso para pensum 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar {{ curso.curso }}</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:carrera' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Editar curso</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/editar_pensum.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Editar pensum 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar {{ pensum.nombre }}</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'pensum:carrera' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Editar pensum</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pensum/pensum.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Pensum 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de pensum</h1>
    </div>
    <h2>{{ carrera.nombre }}</h2>
    <div class="main-box">
        <table class="main-table">
            <br>
            <a  href="{% url 'pensum:carrera' %}"><button class="logbtn">Regresar</button></a>
            <br>
            <a  href="{% url 'pensum:crear_pensum' %}"><button class="logbtn">Crear pensum</button></a>
            <br>
            <tr>
              <th>Codigo</th>
              <th>Nombre</th>
              <th>Creacion</th>
              <th>Opciones</th>
            </tr>
            {% for pen in pensum %}
            <tr>
              <td>{{ pen.codigo }}</td>
              <td>{{ pen.inicio }}</td>
              <td>{{ pen.creacion }}</td>
              <td>
                <ul>
                    <li><a href="{% url 'pensum:editar_pensum' pen.pk %}">Editar</a></li>
                    <li><a href="{% url 'pensum:ciclo' pen.pk %}">Administrar cursos</a></li>
                </ul>
              </td>
            </tr>
            {% endfor %}
          </table>
        <ul>
    </div>
</div>

{% endblock %}