bdd_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

controlacad/urls.py
from django.contrib import admin
from django.urls import path, include
from Login import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from Login.views import SignupView, RolCreate, RolUpdate, RolModificar


urlpatterns = [
    path('admin/', admin.site.urls),
    # Roles
    path('roles/<int:pk>/editar/', RolUpdate),
    path('roles/<int:pk>/modificar/', RolModificar),
    path('', LoginView.as_view(), name='login'),
    path('roles/', views.RolPage, name='roles'),
    path('create-rol/', views.RolCreate, name='create_rol'),
    # Login - Signup
    path('inicio/', views.HomePage, name='inicio'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Usuarios
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    # Edificios
    path('edificios/', include('edificios.urls', namespace='edificios')),
    # Pensum
    path('inicio/pensum/', include('pensum.urls', namespace="pensum"))
]

edificios/urls.py
from django.urls import path
from .views import (EdificioView, EdificioCrearView, EdificioEditarView,
                    SalonesView, SalonesCrearView, SalonesEditarView,
                    SalonesClasificacionView, SalonesClasificacionCrearView, 
                    SalonesClasificacionEditarView)


app_name = 'edificios'

urlpatterns = [
    #Edificios
    path('', EdificioView.as_view(), name='edificio'),
    path('crear/', EdificioCrearView.as_view(), name='edificio_crear'),
    path('<int:pk>/editar/', EdificioEditarView.as_view(), name='edificio_editar'),
    #Salones
    path('salones/', SalonesView.as_view(), name='salones'),
    path('salones/crear/', SalonesCrearView.as_view(),
         name='salones_crear'),
    path('salones/<int:pk>/editar/', SalonesEditarView.as_view(),
         name='salones_editar'),
    #Clasificación de salones
    path('salones/clasificacion', SalonesClasificacionView.as_view(),
         name='clasificacionSalones'),
    path('salones/clasificacion/crear/',
         SalonesClasificacionCrearView.as_view(), name='salon_clasificacion_crear'),
    path('salones/clasificacion/<int:pk>/editar/',
         SalonesClasificacionEditarView.as_view(), name='salon_clasificacion_editar'),
         
    ]

pensum/urls.py
from django.urls import path
from .views import carrera, crear_carrera, pensum, curso, editar_carrera, crear_curso, editar_curso
from .views import crear_pensum, editar_pensum, ciclo, crear_ciclo, curso_pensum, agregar_curso, editar_curso_pensum

app_name = "pensum"

urlpatterns = [
    path('carrera/', carrera, name='carrera'),
    path('crear_carrera/', crear_carrera, name='crear_carrera'),
    path('editar_carrera/<pk>', editar_carrera, name='editar_carrera'),
    path('crear_pensum/', crear_pensum, name='crear_pensum'),
    path('pensum/<pk>', pensum, name='pensum'),
    path('editar_pensum/<pk>', editar_pensum, name='editar_pensum'),
    path('curso/', curso, name='curso'),
    path('crear_curso/', crear_curso, name='crear_curso'),
    path('editar_curso/<pk>', editar_curso, name='editar_curso'),
    path('ciclo/<pk>', ciclo, name='ciclo'),
    path('crear_ciclo/', crear_ciclo, name='crear_ciclo'),
    path('curso_pensum/<pk>', curso_pensum, name='curso_pensum'),
    path('agregar_curso/', agregar_curso, name='agregar_curso'),
    path('editar_curso_pensum/<pk>', editar_curso_pensum, name='editar_curso_pensum'),
]

edificios/models.py
from django.db import models

# Create your models here.

class Edificio(models.Model):
    nombre = models.CharField(max_length=20)
    salones = models.IntegerField(default=0, null=False)
    niveles = models.IntegerField(default=0, null=False)
    fecha_creacion = models.DateField(auto_now=True, null=False)
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"

class Salon_clasificacion(models.Model):
    nombre = models.CharField(max_length=20)
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"

class Salon(models.Model):
    nombre = models.CharField(max_length=20)
    edificio = models.ForeignKey("Edificio", on_delete=models.SET_DEFAULT,null=True, default="")
    capacidad = models.IntegerField(default=0,null=False)
    salon_clasificacion = models.ForeignKey("Salon_clasificacion", on_delete=models.SET_DEFAULT,null=True, default="")
    habilitado = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre}"

edificios/forms.py
from django import forms
from .models import Edificio, Salon, Salon_clasificacion

class EdificioCreateForm(forms.ModelForm):
    class Meta:
        model = Edificio
        fields = ('nombre',
                  'salones',
                  'niveles',
                  )


class EdificioUpdateForm(forms.ModelForm):
    class Meta:
        model = Edificio
        fields = ('nombre',
                  'salones',
                  'niveles',
                  'habilitado',
                  )



class SalonCreateForm(forms.ModelForm):
    class Meta:
        model = Salon
        fields = ('nombre',
                  'capacidad',
                  'edificio',
                  'salon_clasificacion',
                  )


class SalonUpdateForm (forms.ModelForm):
    class Meta:
        model = Salon
        fields = ('nombre',
                  'capacidad',
                  'edificio',
                  'salon_clasificacion',
                  'habilitado',
                  )


class SalonClasiCreateForm(forms.ModelForm):
    class Meta:
        model = Salon_clasificacion
        fields = ('nombre',
                  )

class SalonClasiUpdateForm(forms.ModelForm):
    class Meta:
        model = Salon_clasificacion
        fields = ('nombre',
                  'habilitado',
                  )

edificios/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.shortcuts import render, redirect, reverse
from .forms import (EdificioCreateForm, EdificioUpdateForm, 
                    SalonCreateForm, SalonUpdateForm, 
                    SalonClasiCreateForm, SalonClasiUpdateForm)
from .models import Edificio, Salon, Salon_clasificacion


# Create your views here.

# Vistas para Edificio
class EdificioView(generic.ListView):
    template_name = 'edificio/edificio.html'
    queryset = Edificio.objects.all()
    context_object_name = 'edificios'


class EdificioCrearView(generic.CreateView):
    template_name = 'edificio/edificioCrear.html'
    form_class = EdificioCreateForm

    def get_success_url(self):
        return reverse('edificios:edificio')
    
    def form_valid(self, form):
        nuevo_edificio = form.save(commit=False)
        nuevo_edificio.save()
        return super(EdificioCrearView, self).form_valid(form)
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        return context

class EdificioEditarView(generic.UpdateView):
    template_name = 'edificio/edificioEditar.html'
    queryset = Edificio.objects.all()
    form_class = EdificioUpdateForm

    def get_success_url(self):
        return reverse('edificios:edificio')

# Vistas para Salon

class SalonesView(generic.ListView):
    template_name = 'salones/salones.html'
    queryset = Salon.objects.all()
    context_object_name = 'salones'


class SalonesCrearView(generic.CreateView):
    template_name = 'salones/salonesCrear.html'
    form_class = SalonCreateForm

    def get_success_url(self):
        return reverse('edificios:salones')
    
    def form_valid(self, form):
        nuevo_salon = form.save(commit=False)
        nuevo_salon.save()
        return super(SalonesCrearView, self).form_valid(form)
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        return context

class SalonesEditarView(generic.UpdateView):
    template_name = 'salones/salonesEditar.html'
    queryset = Salon.objects.all()
    form_class = SalonUpdateForm

    def get_success_url(self):
        return reverse('edificios:salones')

# Vistas para Clasificacion Salon

class SalonesClasificacionView(generic.ListView):
    template_name = 'clasificacion/salonesClasificacion.html'
    queryset = Salon_clasificacion.objects.all()
    context_object_name = 'clasificacionSalones'

class SalonesClasificacionCrearView(generic.CreateView):
    template_name = 'clasificacion/salonesClasificacionCrear.html'
    form_class = SalonClasiCreateForm

    def get_success_url(self):
        return reverse('edificios:clasificacionSalones')
    
    def form_valid(self, form):
        nueva_clasi = form.save(commit=False)
        nueva_clasi.save()
        return super(SalonesClasificacionCrearView, self).form_valid(form)
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        return context

class SalonesClasificacionEditarView(generic.UpdateView):
    template_name = 'clasificacion/salonesClasificacionEditar.html'
    queryset = Salon_clasificacion.objects.all()
    form_class = SalonClasiUpdateForm

    def get_success_url(self):
        return reverse('edificios:clasificacionSalones')

edificios/templates/salones/salones.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Salon 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Adminsitración de salones</h1>
    </div>
    <div class="main-box">
        <table class="main-table">
            <br>
            <a  href="{% url 'edificios:clasificacionSalones' %}"><button class="logbtn">Clasificación</button></a>
            <br>
            <a  href="{% url 'edificios:salones_crear' %}"><button class="logbtn">Crear</button></a>
            <br>
            <tr>
                <th>Salon</th>
                <th>edificio</th>
                <th>Opciones</th>
            </tr>
            {% for salon in salones %}
            <tr>
                <td>{{ salon.nombre }}</td>
                <td>{{ salon.edificio }}</td>
                <td>
                    <ul>
                        <li><a href="{% url 'edificios:salones_editar' salon.pk %}">Editar</a></li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </table>
        <br>
        <a  href="{% url 'edificios:edificio' %}"><button class="logbtn">Regresar</button></a>
    </div>
</div>

{% endblock %}

edificios/templates/salones/salonesCrear.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Salon 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Crear salones</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'edificios:salones' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Crear</button>
        </form>
        <br>
        <a  href="{% url 'edificios:salon_clasificacion_crear' %}"><button class="logbtn">SC +</button></a>
    </div>
</div>

{% endblock %}

edificios/templates/salones/salonesEditar.html
{% extends 'main/layout.html'%}
{% load static %}

{% block title %}
    Salon 
{% endblock %}

{% block content %}

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar salones</h1>
    </div>

<div class="main-content">
    <div class="initial">
        <h1 class="title">Editar {{ salon.nombre }}</h1>
    </div>
    <div class="main-box">
        <br>
        <a  href="{% url 'edificios:salones' %}"><button class="logbtn">Regresar</button></a>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="logbtn" type="submit">Guardar</button>
        </form>
        <br>
        <a  href="{% url 'edificios:salon_clasificacion_crear' %}"><button class="logbtn">SC +</button></a>
    </div>
</div>

{% endblock %}